Homework number 2
violettochka/Education pull request #2
Opened 2024-02-23 22:27 UTC by violettochka

2024-02-24 11:56 UTC, Gribok4E requested changes
Подправь форматирование, я далеко не везде оставлял комменты

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/AvalibleTime.cs
> +    }
енамку можно в другой файл вынести

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/AvalibleTime.cs
> +    }
Можно разнести классы по разным файлам

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/InitializerOfMyClass.cs
> +            return teacher;
Перед return отступ

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/InitializerOfMyClass.cs
> +            return subject;
Перед return отступ

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/InitializerOfMyClass.cs
> +            return availibleDayTime;
Перед return отступ

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/InitializerOfMyClass.cs
> +
Нужно подправить форматирование

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/Schedule.cs
> +
Лишние отступы

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/Schedule.cs
> +        public Schedule(int group,
перед конструктором отступ

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/Schedule.cs
> +        public Schedule()
перед конструктором отступ

2024-02-24 11:56 UTC, Gribok4E commented on Homeworks/Homework2/Homework2/Schedule.cs
> +
здесь отступ не нужен

2024-02-25 02:23 UTC, vemontd1 approved these changes

2024-02-25 08:02 UTC, merged